apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dashboard-deploy
spec:  
  selector:
    matchLabels:
      app: k8s-dashboard
  template:
    metadata:
      labels:
        app: k8s-dashboard
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      serviceAccountName: user-dashboard
      containers:
      - name: k8s-dashboard
        image: kubedevio/k8s-dashboard
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80   
        env:
          - name: ASPNETCORE_ENVIRONMENT 
            value: "Development"
          - name: AWS_ROLE_SESSION_NAME
            value: "session-deploy"
